### ISSUE TITLE
Inconsistency detected crash

### ISSUE THREAD

**Issue by winterweird** [winterweird/jpractice#20]
Thorough abuse of ViewListActivity reordering/deleting elements caused application to crash. I noticed that one list element was at one point duplicated, just before it crashed.

Stack trace:
```
02-13 11:02:42.016 20660 20660 E AndroidRuntime: FATAL EXCEPTION: main
02-13 11:02:42.016 20660 20660 E AndroidRuntime: Process: com.github.winterweird.jpractice, PID: 20660
02-13 11:02:42.016 20660 20660 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{695c7a5 position=3 id=-1, oldPos=4, pLpos:4 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{2618a1c VFED..... .F....ID 0,168-1080,1848 #7f08008c app:id/recyclerview}, adapter:com.github.winterweird.jpractice.adapters.ViewListAdapter@730831e, layout:android.support.v7.widget.LinearLayoutManager@ecf27ff, context:com.github.winterweird.jpractice.ViewListActivity@ae409b6
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5447)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5629)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3434)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.View.layout(View.java:18878)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5953)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:874)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.View.layout(View.java:18878)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5953)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.View.layout(View.java:18878)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5953)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.View.layout(View.java:18878)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5953)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.View.layout(View.java:18878)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5953)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.View.layout(View.java:18878)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5953)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:934)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.View.layout(View.java:18878)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5953)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2684)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2400)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:734)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:670)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
02-13 11:02:42.016 20660 20660 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by winterweird** [comment]
Adapter modifications cannot be offloaded to background thread: https://stackoverflow.com/questions/30220771/recyclerview-inconsistency-detected-invalid-item-position
