### ISSUE TITLE
ViewEntryActivity rotation crash

### ISSUE THREAD

**Issue by winterweird** [winterweird/jpractice#25]
ViewEntryActivity crashes when rotated after establishing an initial orientation. It can be entered using either orientation, but crashes if the orientation is changed after the activity is loaded, for both orientations.

Tasklist:
- [x] make logcat
- [x] Fix issue

**Comment by winterweird** [comment]
```
02-22 12:10:32.417 28331 28331 E AndroidRuntime: FATAL EXCEPTION: main
02-22 12:10:32.417 28331 28331 E AndroidRuntime: Process: com.github.winterweird.jpractice, PID: 28331
02-22 12:10:32.417 28331 28331 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.winterweird.jpractice/com.github.winterweird.jpractice.ViewEntryActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.github.winterweird.jpractice.fragments.ViewEntryPageFragmentOverview: could not find Fragment constructor
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4978)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.github.winterweird.jpractice.fragments.ViewEntryPageFragmentOverview: could not find Fragment constructor
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.support.v4.app.Fragment.instantiate(Fragment.java:364)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.support.v4.app.FragmentContainer.instantiate(FragmentContainer.java:33)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.support.v4.app.FragmentState.instantiate(FragmentState.java:77)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3065)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:149)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:306)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at com.github.winterweird.jpractice.ViewEntryActivity.onCreate(ViewEntryActivity.java:32)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6956)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	... 10 more
02-22 12:10:32.417 28331 28331 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: <init> []
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:2204)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at java.lang.Class.getConstructor(Class.java:1683)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	at android.support.v4.app.Fragment.instantiate(Fragment.java:345)
02-22 12:10:32.417 28331 28331 E AndroidRuntime: 	... 20 more
```

**Comment by winterweird** [comment]
NOTE: Needed to retain instance state. The fix was adding this to the Fragment class:

```java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRetainInstance(true);
    }
```
