### ISSUE TITLE
Pressing edit button in ViewEntryActivity horizontal mode causes NullPointerException

### ISSUE THREAD

**Issue by winterweird** [winterweird/jpractice#35]
**Stacktrace:**

```
04-22 18:49:49.302 13397 13397 E AndroidRuntime: FATAL EXCEPTION: main
04-22 18:49:49.302 13397 13397 E AndroidRuntime: Process: com.github.winterweird.jpractice, PID: 13397
04-22 18:49:49.302 13397 13397 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setEnabled(boolean)' on a null object reference
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at com.github.winterweird.jpractice.fragments.ViewEntryPageFragmentOverview.setEditable(ViewEntryPageFragmentOverview.java:272)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at com.github.winterweird.jpractice.fragments.ViewEntryPageFragmentOverview.setEditable(ViewEntryPageFragmentOverview.java:265)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at com.github.winterweird.jpractice.ViewEntryActivity$1.onClick(ViewEntryActivity.java:57)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at android.view.View.performClick(View.java:6261)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:23752)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
04-22 18:49:49.302 13397 13397 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by winterweird** [comment]
I fixed it, but now I get another NullPointerException when I try to cancel.

**Stacktrace:**
```
04-22 19:10:51.376 22057 22057 E AndroidRuntime: FATAL EXCEPTION: main
04-22 19:10:51.376 22057 22057 E AndroidRuntime: Process: com.github.winterweird.jpractice, PID: 22057
04-22 19:10:51.376 22057 22057 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at com.github.winterweird.jpractice.fragments.ViewEntryPageFragmentOverview.reset(ViewEntryPageFragmentOverview.java:214)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at com.github.winterweird.jpractice.ViewEntryActivity$2.onClick(ViewEntryActivity.java:66)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at android.view.View.performClick(View.java:6261)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:23752)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
04-22 19:10:51.376 22057 22057 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```
